### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by akalendarov** [Alke-Games/Dauphine#1]
Hello. I'm running Ubuntu 14.04 and want to install your application. But during compilation i get an error:

In file included from /Dauphine/include/Animation.h:4:0,
                 from src/Animation.cpp:1:
/Dauphine/include/SDLWrapper.h:6:28: fatal error: SDL2/SDL_image.h: No such file or directory
 #include <SDL2/SDL_image.h>

I installed libsdl2-dev and libsdl2-2.0-0 but still no effect.
Can you help me please?

**Comment by CaioIcy** [comment]
Hi!

Besides SDL2, you need the libraries SDL_Image, SDL_Mixer, SDL_TTF and SDL2_GFX (all of them for SDL2, not the previous versions).

If you have any more trouble, feel free to comment more here. If you manage to compile, let us know!

**Comment by akalendarov** [comment]
I've installed libsdl2-image-dev, libsdl2-mixer-dev,  libsdl2-ttf-dev and libsdl2-gfx-dev. Now I have a trouble with

#include "lua.hpp"

In my case it can be fixed by replacing by

#include "lua5.2/lua.hpp"

**Comment by ricardogtx** [comment]
To fix that, you need to edit lines 4-7 in the Makefile. There, you configure your lua directory. This way you don't need to change the source code.

**Comment by akalendarov** [comment]
Compilation was successful!)

Can you tell me how to move?

**Comment by CaioIcy** [comment]
You can either use a joystick (playstation/xbox controller) or the keyboard. So far the controls aren't final, but as they are now:

**Move**: Directional Arrows (Left, Right)
**Jump**: Spacebar
**Roll**: C
**Crouch**: V
**Throw potion**: while holding down to aim, use Left/A Right/D to aim, and throw with Spacebar

When the controls are 100% we will update the README.
